POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "Max Verstappen",
  "dateOfBirth": "1989-9-02",
  "ssn": "38921-222J",
  "gender": "male",
  "occupation": "Formula driver"
}